api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
    swagger:
        versions: [3]
    eager_loading:
        force_eager: false
